### ISSUE TITLE
OGM model

### ISSUE THREAD

**Issue by msgre** [cesko-digital/zacni-ucit#10]
@jakubbares potrebuju radu. Ukaz mi prosim, jak se pracuje s `py2neo.GraphObject` objekty a relacemi.

Zkusil jsem si takto nadefinovat modely:

```python
from django.conf import settings
from py2neo.ogm import GraphObject, Property, RelatedTo

class BaseModel(GraphObject):
    __primarykey__ = "id"
    
    id = Property()

    def __init__(self, **kwargs):
        for key, value in kwargs.items():
            if hasattr(self, key):
                setattr(self, key, value)

    def save(self):
        settings.GRAPH.push(self)


class CollegeModel(BaseModel):
    name = Property()


class FacultyModel(BaseModel):
    name = Property()
    college = RelatedTo(CollegeModel)
```

Kdyz pak vytvorim instanci `CollegeModel` a ulozim ji, vsecko probehne jak ma:

```python
c = CollegeModel(id=1, name="prvni")
c.save()
```

Zadny error to nevyhodi, pres web rozhrani Neo4j si dokazu model vytahnout `MATCH (n) RETURN n`. Myslim ze to je ok.

Dal ale nevim. Kdyz se snazim podobne vytvorit zaznam o fakulte (s vazbou na vysokou skolu), ulozi se mi jen zaznam s fakultou, ale bez vazby:

```python
f = FacultyModel(id=1, name="kolej", college=c)
f.save()
```

Jak se to dela?

**Comment by jakubbares** [comment]
Koukni do ogm_example.py. Tam je ukladani napr pro komponentu Statetement ktere je velmi komplexni

**Comment by jakubbares** [comment]
College je entita ktera je pripojena pres vztah. (RelatedTo) takze to nemuzes davat jako property

**Comment by msgre** [comment]
Kde ten soubor je? Postni tu prosim link...

**Comment by jakubbares** [comment]
https://github.com/cesko-digital/zacni-ucit/blob/master/backend/zacniucit/ogm_example.py

**Comment by msgre** [comment]
Vyreseno genericky -- backend obsahuje mixinu [`GraphModel`](https://github.com/cesko-digital/zacni-ucit/blob/master/backend/common/models.py), diky ktere standardni Django modely ziskaji funkcionalitu potrebnou pro publikovani dat do grafove databaze.
